[package]
name = "ockam_command"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "ockam"

[dependencies]
bunt = "0.2.6"
clap = { version = "2.33.3" }
comfy-table = "5.0.0"
config = { version = "0.11.0", features = ["toml"] }
ctrlc = "3.2.1"
dotenv = "0.15.0"
exitcode = "1.1.2"
human-panic = "1.0.3"
indicatif = "0.16.2"
log = "0.4.14"
ockam = { version = "0.39.0", path = "../ockam" }
serde = "1.0.130"
stderrlog = "0.5.1"
thiserror = "1.0.30"
