name: Nix Store Upload
description: Nix Store Upload
inputs:
  flake_nix_path:
    description: Flake Nix Path
    required: true

runs:
  using: composite
  steps:
    - name: Cache Nix store
      shell: bash
      run: nix copy --to /tmp/nixcache ${{ inputs.flake_nix_path }}
