
version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "ci:"
    schedule:
      interval: "daily"
    labels:
      - "Type: Dependencies"
      - "Component: CI/CD"

  # Maintain dependencies for rust crates
  - package-ecosystem: "cargo"
    directory: "/"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"
    labels:
      - "Type: Dependencies"
      - "Implementation: Rust"

  # Maintain dependencies for typescript packages
  - package-ecosystem: "npm"
    directory: "/implementation/typescript"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"
    labels:
      - "Type: Dependencies"
      - "Implementation: Typescript"

  # Maintain dependencies for elixir ockam application
  - package-ecosystem: "mix"
    directory: "/implementations/elixir/ockam/ockam"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"
    labels:
      - "Type: Dependencies"
      - "Implementation: Elixir"

  # Maintain dependencies for elixir ockam_services application
  - package-ecosystem: "mix"
    directory: "/implementations/elixir/ockam/ockam_services"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"
    labels:
      - "Type: Dependencies"
      - "Implementation: Elixir"

  # Maintain dependencies for elixir ockam_metrics application
  - package-ecosystem: "mix"
    directory: "/implementations/elixir/ockam/ockam_metrics"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"
    labels:
      - "Type: Dependencies"
      - "Implementation: Elixir"

  # Maintain dependencies for elixir ockam_healthcheck application
  - package-ecosystem: "mix"
    directory: "/implementations/elixir/ockam/ockam_healthcheck"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"
    labels:
      - "Type: Dependencies"
      - "Implementation: Elixir"

  # Maintain dependencies for elixir ockam_cloud_node application
  - package-ecosystem: "mix"
    directory: "/implementations/elixir/ockam/ockam_cloud_node"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"
    labels:
      - "Type: Dependencies"
      - "Implementation: Elixir"

  # Maintain dependencies for elixir ockam_kafka application
  - package-ecosystem: "mix"
    directory: "/implementations/elixir/ockam/ockam_kafka"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"
    labels:
      - "Type: Dependencies"
      - "Implementation: Elixir"

  # Maintain dependencies for elixir ockam_vault_software application
  - package-ecosystem: "mix"
    directory: "/implementations/elixir/ockam/ockam_vault_software"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"
    labels:
      - "Type: Dependencies"
      - "Implementation: Elixir"


  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /examples/rust/ockam_kafka
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /examples/rust/tcp_inlet_and_outlet
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: /implementations/rust/ockam/ockam_examples/example_projects/ssh_credentials
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /implementations/typescript/.yarn/sdks/typescript
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /implementations/typescript/ockam/ockam
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /implementations/typescript
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /integrations/suborbital/demo
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: /integrations/suborbital/helloworld-rs
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /tools/docker/builder
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /tools/docker/cloud-node
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /tools/docker/healthcheck
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /tools/docker/ockam
    schedule:
      interval: daily
