[package]
name = "ockam_message_derive"
categories = ["cryptography", "asynchronous", "authentication","network-programming"]
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_message_derive"
readme = "README.md"
keywords = ["ockam", "crypto", "macro", "proc-macro", "attribute"]
description = """
Ockam Message trait [derive] macro.
"""
exclude = [
    "DEVELOP.md",
    "LICENSE"
]

[lib]
proc-macro = true

[features]
default = []

no_std = []
alloc = []

[dependencies]
quote = "1.0"
syn = {version = "1.0", features = ["full"]}
