push = false
tag = false
verify = true
sign-commit = true
pre-release-commit-message = "chore(rust): crate release {{crate_name}} version {{version}}"
pre-release-replacements = [
    { file = "CHANGELOG.md", min = 0, search = "## unreleased", replace = "## {{version}} - {{date}}" },
]
