dev-version = true
push = true
tag = true
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="Unreleased\n### Added\n### Changed\n### Removed\n\n\n## v{{version}} - {{date}}"},
  {file="README.md", search="= \".*\"", replace="= \"{{version}}\""},
]
