dev-version = true
push = true
tag = true
pre-release-replacements = [
  {file="CHANGELOG.md", min=0, search="Unreleased", replace="v{{version}} - {{date}}"},
  {file="README.md", min=0, search="= \".*\"", replace="= \"{{version}}\""},
]
