name: Nix Cache
description: Cache Nix File To Temporary Directory

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "Hello freaky"
        # sudo systemctl stop nix-daemon
        # sudo chmod -R 777 /nix
        # sudo cp -r /nix /tmp/nix-cache

        # sudo rm -rf /tmp/nix-cache/var/nix/daemon-socket/socket
        # sudo rm -rf /tmp/nix-cache/var/nix/userpool
        # sudo rm -rf /tmp/nix-cache/var/nix/gc.lock
        # sudo rm -rf /tmp/nix-cache/var/nix/db/big-lock
        # sudo rm -rf /tmp/nix-cache/var/nix/db/reserved
        # sudo rm -rf /tmp/nix-cache/var/nix/userpool2

        # # tar -zcvf /tmp/nix-cache /tmp/nix-cache-dir/
