name: All

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/all.yml'
      - '**.gradle'
      - 'tools/gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/actions/**'
  push:
    paths:
      - '.github/workflows/all.yml'
      - '**.gradle'
      - 'tools/gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/actions/**'
  schedule:
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: All - Build
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/build-trust/ockam-builder@sha256:55b60f7efe2c48c098bd52db2e9dbf0a1b6f6c7e583ff278987d2d11adea04e2
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # v2.0.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: ./.github/actions/gradle_cache
      - uses: ./.github/actions/cargo_home_cache
      - uses: ./.github/actions/cargo_target_dir_cache
      - uses: ./.github/actions/elixir_cache
      - run: ./gradlew build -Pmode=release
      - uses: ./.github/actions/cargo_target_dir_pre_cache

  list_gradle_tasks:
    name: All - List Gradle Tasks
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]
        java: [8, 11, 16, 17]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # v2.0.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc
        with:
          distribution: 'temurin'
          check-latest: true
          java-version: ${{ matrix.java }}
      - uses: ./.github/actions/gradle_cache
      - run: ./gradlew tasks --all
