name: Code Freeze CI

permission:
  contents: read

on: 
  workflow_dispatch
    inputs:
      branch_name:
        description: Branch Name To Create Pull Request
        required: true
      set_pr_state:
        type: choice
        description: Set Mergify PR Freeze State
        default: freeze
        options:
        - freeze
        - unfreeze

defaults:
  run:
    shell: bash

jobs:
  code_freeze_automation:
    name: Code Freeze Automation
    runs-on: ubuntu-22.04
    environment: release
    permission:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0

      - name: Import GPG key
        uses: build-trust/.github/actions/import_gpg@a6377d3c2dac878b92a0da26cdf3da2856c64840
        with:
          gpg_private_key: '${{ secrets.GPG_PRIVATE_KEY }}'
          gpg_password: '${{ secrets.GPG_PASSPHRASE }}'
          gpg_name: '${{ secrets.GPG_USER_NAME }}'
          gpg_email: '${{ secrets.GPG_EMAIL }}'

      - name: Check If Mergify PR State Is Frozen
        id: pr_state
        run: |
          if cat .github/mergify.yml | grep '#- schedule: Mon-Sun'; then
            current_state='unfreeze'
          else
            current_state='freeze'
          fi

          if [[ ${{ github.event.inputs.set_pr_state }} == $current_state ]]; then
            echo "PR state already set to $current_state"
            exit 1
          fi

          echo "current_state=$current_state" >> GITHUB_OUTPUT

      - name: Checkout To Specified Branch
        run: |
          git checkout -B ${{ github.event.inputs.branch_name }}

      - name: Freeze PRs From Being Merged
        if: ${{ steps.pr_state.outputs.current_state == 'freeze' }}
        run: |
          # Uncomment code that enables mergify schedule
          sed -i -e 's/#- schedule: Mon-Sun/- schedule: Mon-Sun/g' .github/mergify.yml

      - name: Unfreeze PRs So That They Can Be Merged
        if: ${{ steps.pr_state.outputs.current_state == 'unfreeze' }}
        run: |
          # Comment code that enables mergify schedule
          sed -i -e 's/- schedule: Mon-Sun/#- schedule: Mon-Sun/g' .github/mergify.yml

      - name: Git Add Mergify Config
        run: |
          git add .github/mergify.yml

          if [[ ${{ steps.pr_state.outputs.current_state }} == 'freeze' ]]; then
            git commit -S -m "ci: freeze mergify"
          else
            git commit -S -m "ci: unfreeze mergify"
          fi

          git push --set-upstream origin ${{ github.event.inputs.branch_name }}
