name: Documentation

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/documentation.yml'
      - 'documentation/use-cases/**.md'
      - 'documentation/guides/rust/**.md'
      - 'tools/docs/**'
      - '**.rs'
      - '**.toml'
      - '**/Cargo.lock'
      - '**.gradle'
      - 'tools/gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/actions/**'
  push:
    paths:
      - '.github/workflows/documentation.yml'
      - 'documentation/use-cases/**.md'
      - 'documentation/guides/rust/**.md'
      - 'tools/docs/**'
      - '**.rs'
      - '**.toml'
      - '**/Cargo.lock'
      - '**.gradle'
      - 'tools/gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/actions/**'
  schedule:
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_examples_in_guides:
    name: Documentation - Check Examples
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/build-trust/ockam-builder@sha256:55b60f7efe2c48c098bd52db2e9dbf0a1b6f6c7e583ff278987d2d11adea04e2
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: ./.github/actions/gradle_cache
      - uses: ./.github/actions/cargo_home_cache
      - uses: ./.github/actions/cargo_target_dir_cache

      - name: Check that example source and guide code blocks match
        id: cache
        run: |
          OCKAM_HOME=$PWD bash -ex tools/docs/check_documentation.sh

          # Only cache rust build if example blocks code was built
          if [[ ls target ]]; then
            echo "is_cached=true" >> $GITHUB_OUTPUT
          fi

      - uses: ./.github/actions/cargo_target_dir_pre_cache
        if: steps.cache.outputs.is_cached
