name: Make

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '.github/workflows/make.yml'
      - '**/Makefile'
      - 'tools/nix/**'
      - '.github/actions/**'
  push:
    paths:
      - '.github/workflows/make.yml'
      - '**/Makefile'
      - 'tools/nix/**'
      - '.github/actions/**'
    branches:
      - develop
  schedule:
    # At 1 am.
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      commit_sha:
        description: Git commit sha, on which, to run this workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: nix develop ./tools/nix --ignore-environment --keep CI --command bash {0}

env:
  CI: true

jobs:
  full_build_in_release_mode:
    name: Make - full_build_in_release_mode
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: ./.github/actions/nix_installer_and_cache
        with:
          cache-unique-id: full_build
        id: nix-installer
      - uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8
      - uses: ./.github/actions/elixir_cache
      - run: make
      - uses: ./.github/actions/nix_upload_store
        if: ${{ steps.nix-installer.outputs.cache-hit != 'true' }}
