name: Make

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '.github/workflows/make.yml'
      - '**/Makefile'
      - 'tools/nix/**'
      - '.github/actions/**'
  push:
    paths:
      - '.github/workflows/make.yml'
      - '**/Makefile'
      - 'tools/nix/**'
      - '.github/actions/**'
    branches:
      - develop
  schedule:
    # We only save cache when a cron job is started, this is to ensure
    # that we don't save cache on every push causing excessive caching
    # and github deleting useful caches we use in our workflows, we now
    # run a cron job every 2 hours so as to update the cache store with the
    # latest data so that we don't have stale cache.
    - cron: "0 */2 * * *"
  workflow_dispatch:
    inputs:
      commit_sha:
        description: Git commit sha, on which, to run this workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  full_build_in_release_mode:
    name: Make - full_build_in_release_mode
    runs-on: ubuntu-22.04
    permissions:
      # Contents permission allows us read this repository.
      packages: read
      contents: read
    container: ghcr.io/metaclips/artifacts-helper@sha256:7fcef0d5025f7cbc17081e04b823e8132c6a92e040d48f87094057b1d4c2a80a
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - name: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -ex
          if ! command -v gh &> /dev/null; then
           `nix shell nixpkgs/nixos-23.11#gh --command gh release download ockam_v0.117.0 -p ockam.x86_64-unknown-linux-musl -R build-trust/ockam` || exit 0
          else
            gh release download ockam_v0.117.0 -p ockam.x86_64-unknown-linux-musl -R build-trust/ockam || exit 0
          fi

          mv ockam.x86_64-unknown-linux-musl ockam
          chmod +x ockam
          ./ockam --version

          ls
