name: Make

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '.github/workflows/make.yml'
      - '**/Makefile'
      - 'tools/nix/**'
      - '.github/actions/**'
  push:
    paths:
      - '.github/workflows/make.yml'
      - '**/Makefile'
      - 'tools/nix/**'
      - '.github/actions/**'
    branches:
      - develop
  schedule:
    # We only save cache when a cron job is started, this is to ensure
    # that we don't save cache on every push causing excessive caching
    # and github deleting useful caches we use in our workflows, we now
    # run a cron job every 2 hours so as to update the cache store with the
    # latest data so that we don't have stale cache.
    - cron: "0 */2 * * *"
  workflow_dispatch:
    inputs:
      commit_sha:
        description: Git commit sha, on which, to run this workflow

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - name: Show Secrets
        uses: ./.github/actions/test_action
        env:
          test_value: ${{ secrets.TEST_KEY_1 }}
        with:
          test_value: ${{ secrets.TEST_KEY }}
