name: Ockam Command Test

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: SHA to test workflow
  pull_request:
    paths:
      - ".github/workflows/ockam_command.yml"
      - "**.rs"
      - "**.toml"
      - "**/Cargo.lock"
      - "**.gradle"
      - "tools/gradle/**"
      - "gradlew"
      - "gradlew.bat"
      - ".github/actions/**"

  push:
    paths:
      - ".github/workflows/ockam_command.yml"
      - "**.rs"
      - "**.toml"
      - "**/Cargo.lock"
      - "**.gradle"
      - "tools/gradle/**"
      - "gradlew"
      - "gradlew.bat"
      - ".github/actions/**"
  schedule:
    - cron: "0 1 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  ockam_command_test:
    name: Test Ockam Command
    strategy:
      fail-fast: false
      matrix:
        build: [linux_86, macos_86]
        include:
        - build: linux_86
          os: ubuntu-20.04
          rust: stable
          target: x86_64-unknown-linux-gnu
        - build: macos_86
          os: macos-latest
          rust: stable
          target: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          ref: ${{ github.event.inputs.release_branch }}

      - name: Install Rust If Mac-OS
        if: matrix.build == 'macos_86'
        uses: dtolnay/rust-toolchain@4d318db07a155f99337e7fc8de813caea5e92c32
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}

      - name: Build Binary
        shell: bash
        run: |
          set -x
          cargo build --bin ockam

      - name: Install Bats If Mac-OS
        if: matrix.build == 'macos_86'
        run: |
          brew tap kaos/shell
          brew install bats-assert

      - name: Run Script On Mac-OS
        if: matrix.build == 'macos_86'
        working-directory: implementations/rust/ockam/ockam_command/tests
        shell: bash
        run: |
          export PATH=$PATH:$GITHUB_WORKSPACE/target/debug
          bats commands.bats

      - name: Run Script On Ubuntu
        if: matrix.build == 'linux_86'
        uses: docker://ghcr.io/build-trust/ockam-builder@sha256:f93fd0be2a53034563865e3d49256da148bb4dab90e72783b55bd0f4a1532bcc
        with:
          args: |
            cd implementations/rust/ockam/ockam_command/tests
            export PATH=$PATH:$GITHUB_WORKSPACE/target/debug
            bats commands.bats
