name: OSV-Scanner

# Default branch is "develop"
on:
  pull_request:
  push:
    branches: [ develop ]
  merge_group:

# Declaring default permissions as read only.
permissions: read-all

jobs:
  scan-pr:
    uses: "google/osv-scanner/.github/workflows/osv-scanner-reusable-pr.yml@b683547c9364ff72414a0377ddfaf5317a0f40e1"
