name: Rust

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: SHA to test workflow
  pull_request:
    paths:
      - '.github/workflows/rust.yml'
      - '**.rs'
      - '**.toml'
      - '**/Cargo.lock'
      - '**.gradle'
      - 'tools/gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/actions/**'
  push:
    paths:
      - '.github/workflows/rust.yml'
      - '**.rs'
      - '**.toml'
      - '**/Cargo.lock'
      - '**.gradle'
      - 'tools/gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/actions/**'
  schedule:
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_cargo_fmt_check:
    name: Rust - Lint Formatting
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:e874d5c6323736e18c666aa26d15188b17f2342fee41bf20bdff463ace9bc4ae
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: ./.github/actions/gradle_cache
      - uses: Swatinem/rust-cache@842ef286fff290e445b90b4002cc9807c3669641
      - run: cd implementations/rust && ../../gradlew lint_cargo_fmt_check

  lint_cargo_clippy:
    name: Rust - Lint with Cargo Clippy
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:e874d5c6323736e18c666aa26d15188b17f2342fee41bf20bdff463ace9bc4ae
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: ./.github/actions/gradle_cache
      - uses: Swatinem/rust-cache@842ef286fff290e445b90b4002cc9807c3669641
      - run: cd implementations/rust && ../../gradlew lint_cargo_clippy

  lint_cargo_deny:
    name: Rust - Lint with Cargo Deny
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:e874d5c6323736e18c666aa26d15188b17f2342fee41bf20bdff463ace9bc4ae
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: ./.github/actions/gradle_cache
      - uses: Swatinem/rust-cache@842ef286fff290e445b90b4002cc9807c3669641
      - run: cd implementations/rust && ../../gradlew lint_cargo_deny

  build_docs:
    name: Rust - Build Documentation
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:e874d5c6323736e18c666aa26d15188b17f2342fee41bf20bdff463ace9bc4ae
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: ./.github/actions/gradle_cache
      - uses: Swatinem/rust-cache@842ef286fff290e445b90b4002cc9807c3669641
      - run: cd implementations/rust && ../../gradlew build_docs

  build:
    name: Rust - Build
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:e874d5c6323736e18c666aa26d15188b17f2342fee41bf20bdff463ace9bc4ae
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: ./.github/actions/gradle_cache
      - uses: Swatinem/rust-cache@842ef286fff290e445b90b4002cc9807c3669641
      - run: cd implementations/rust && ../../gradlew build

  build_examples:
    name: Rust - Build Examples
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:e874d5c6323736e18c666aa26d15188b17f2342fee41bf20bdff463ace9bc4ae
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: ./.github/actions/gradle_cache
      - uses: Swatinem/rust-cache@842ef286fff290e445b90b4002cc9807c3669641
      - run: cd implementations/rust && ../../gradlew build_examples

  test:
    name: Rust - Test
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:e874d5c6323736e18c666aa26d15188b17f2342fee41bf20bdff463ace9bc4ae
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: ./.github/actions/gradle_cache
      - uses: Swatinem/rust-cache@842ef286fff290e445b90b4002cc9807c3669641
      - run: cd implementations/rust && ../../gradlew test

  check_no_std:
    name: Rust - Check Features - no_std alloc software_vault
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:e874d5c6323736e18c666aa26d15188b17f2342fee41bf20bdff463ace9bc4ae
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: ./.github/actions/gradle_cache
      - uses: Swatinem/rust-cache@842ef286fff290e445b90b4002cc9807c3669641
      - run: |
          cd implementations/rust/ockam/ockam
          RUSTFLAGS='-Dwarnings' cargo check --no-default-features --features 'no_std alloc software_vault'

  check_cargo_update:
    name: Rust - Check Cargo Update
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:e874d5c6323736e18c666aa26d15188b17f2342fee41bf20bdff463ace9bc4ae
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: ./.github/actions/gradle_cache
      - uses: Swatinem/rust-cache@842ef286fff290e445b90b4002cc9807c3669641
      - run: |
          cd examples/rust/get_started
          rm -rf Cargo.lock
          cargo update
          RUSTFLAGS='-Dwarnings' cargo check

  check_nightly:
    name: Rust - Nightly Check
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:e874d5c6323736e18c666aa26d15188b17f2342fee41bf20bdff463ace9bc4ae
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: ./.github/actions/gradle_cache
      - run: rustup default nightly
      - uses: Swatinem/rust-cache@842ef286fff290e445b90b4002cc9807c3669641
      - run: RUSTFLAGS='-Dwarnings' cargo check

  build_nightly:
    name: Rust - Nightly Build
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:e874d5c6323736e18c666aa26d15188b17f2342fee41bf20bdff463ace9bc4ae
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: ./.github/actions/gradle_cache
      - run: rustup default nightly
      - uses: Swatinem/rust-cache@842ef286fff290e445b90b4002cc9807c3669641
      - run: cd implementations/rust && ../../gradlew build

  test_nightly:
    name: Rust - Nightly Test
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:e874d5c6323736e18c666aa26d15188b17f2342fee41bf20bdff463ace9bc4ae
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - uses: ./.github/actions/gradle_cache
      - run: rustup default nightly
      - uses: Swatinem/rust-cache@842ef286fff290e445b90b4002cc9807c3669641
      - run: cd implementations/rust && ../../gradlew test
