name: OSSF Scorecards

permissions:
  contents: read

on:
  branch_protection_rule:
  push:
    branches:
      - develop
  schedule:
    # At 1am on Monday
    - cron: '0 1 * * 1'

jobs:
  analyze:
    name: OSSF Scorecards - analyze
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write # Needed to upload results to code-scanning dashboard.
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Analyze
        uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          publish_results: true

      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@f6091c0113d1dcf9b98e269ee48e8a7e51b7bdd4
        with:
          sarif_file: results.sarif
