name: OSSF Scorecards

permissions:
  contents: read

on:
  branch_protection_rule:
  push:
    branches:
      - develop
  schedule:
    # At 1am on Monday
    - cron: '0 1 * * 1'

jobs:
  analyze:
    name: OSSF Scorecards - analyze
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write # Needed to upload results to code-scanning dashboard.
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
        with:
          persist-credentials: false

      - name: Analyze
        uses: ossf/scorecard-action@0864cf19026789058feabb7e87baa5f140aac736
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          publish_results: true

      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@530d4feaa9c62aaab2d250371e2061eb7a172363
        with:
          sarif_file: results.sarif
