name: Shellcheck

# shellcheck gives warnings and suggestions for bash/sh shell scripts.
# https://github.com/koalaman/shellcheck

permissions:
  contents: read

on: [workflow_dispatch, pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Shellcheck - Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out ockam repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: Run ShellCheck on all '.sh' files
        run: shellcheck $(find . -iname "*.sh")
