name: Shellcheck

# shellcheck gives warnings and suggestions for bash/sh shell scripts.
# https://github.com/koalaman/shellcheck

permissions:
  contents: read

on: [workflow_dispatch, pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Shellcheck - Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # v2.0.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Check out ockam repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Run ShellCheck on all '.sh' files
        run: shellcheck $(find . -iname "*.sh")
