name: Shfmt

# shfmt formats shell programs
# https://github.com/mvdan/sh#shfmt

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Shfmt - Lint
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/build-trust/ockam-builder@sha256:26c5bba9deca18953043a3a2368ec6bb00035676965432f35be24f88e316363a
    steps:
      - name: Check out ockam repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - name: Run Shfmt on all '.sh' files
        run: shfmt -d $(find . -iname "*.sh")
