name: Typos
on: pull_request

permissions:
  contents: read

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b

      - name: Check spelling
        uses: crate-ci/typos@49d37361a04c8119928f7463881fbc32a1c1abd0
        with:
          config: tools/typos/typos.toml
