name: Typos
on: pull_request

permissions:
  contents: read

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Check spelling
        uses: crate-ci/typos@963c545f6b32b8572104c43605e663e84adbb9fb
        with:
          config: tools/typos/typos.toml
