name: Typos
on: pull_request

permissions:
  contents: read

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Check spelling
        uses: crate-ci/typos@bcafd462cb07ef7ba57e34abf458fe20767e808b
        with:
          config: tools/typos/typos.toml
