name: Typos
on: pull_request

permissions:
  contents: read

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Check spelling
        uses: crate-ci/typos@8e6a4285bcbde632c5d79900a7779746e8b7ea3f
        with:
          config: tools/typos/typos.toml
