name: Typos
on: pull_request

permissions:
  contents: read

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b

      - name: Check spelling
        uses: crate-ci/typos@cfe759ac8dd421e203cc293a373396fbc6fe0d4b
        with:
          config: tools/typos/typos.toml
