name: Typos
on: pull_request

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Check spelling
        uses: crate-ci/typos@7c89b528fdb59c3cdee63aa37cd51e786786f3ed
        with:
          config: tools/typos/typos.toml
