name: Typos
on: pull_request

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Check spelling
        uses: crate-ci/typos@bb139b215005a66aadb4c2bffbc530e939e0ee12
        with:
          config: tools/typos/typos.toml
