name: Typos
on: pull_request

permissions:
  contents: read

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f

      - name: Check spelling
        uses: crate-ci/typos@bcafd462cb07ef7ba57e34abf458fe20767e808b
        with:
          config: tools/typos/typos.toml
