name: Typos
on: pull_request

permissions:
  contents: read

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Check spelling
        uses: crate-ci/typos@d503507db9c5d116c79135435b149cd0f27d726e
        with:
          config: tools/typos/typos.toml
