name: Typos
on: pull_request

permissions:
  contents: read

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Check spelling
        uses: crate-ci/typos@853bbe8898c2e3ce040ba6fb0b2cbb3d0ababec5
        with:
          config: tools/typos/typos.toml
